// shop.js
const products = [
  {
    id: 1,
    title: "Opća fizika 1",
    category: "Napredna fizika",
    price: 13.90,
    image: "./images/book_placeholder.png",
    description: "",
  },
  {
    id: 2,
    title: "Opća fizika 2",
    category: "Napredna fizika",
    price: 11.50,
    image: "./images/book_placeholder.png",
    description: "",
  },
  {
    id: 3,
    title: "Opća fizika 3",
    category: "Napredna fizika",
    price: 14.80,
    image: "./images/book_placeholder.png",
    description: "",
  },
  {
    id: 4,
    title: "Opća fizika 4",
    category: "Matematika",
    price: 14.80,
    image: "./images/book_placeholder.png",
    description: "",
  },
  {
    id: 5,
    title: "Elektrodinamika 1",
    category: "Napredna fizika",
    price: 11.50,
    image: "./images/book_placeholder.png",
    description: "",
  },
  {
    id: 6,
    title: "Elektrodinamika 2",
    category: "Napredna fizika",
    price: 11.50,
    image: "./images/book_placeholder.png",
    description: "",
  },
  {
    id: 7,
    title: "Statistička fizika 1",
    category: "Napredna fizika",
    price: 11.50,
    image: "./images/book_placeholder.png",
    description: "",
  },
  {
    id: 8,
    title: "Statistička fizika 2",
    category: "Napredna fizika",
    price: 11.50,
    image: "./images/book_placeholder.png",
    description: "",
  },
  {
    id: 9,
    title: "Kvantna fizika 1",
    category: "Napredna fizika",
    price: 11.50,
    image: "./images/book_placeholder.png",
    description: "",
  },
  {
    id: 10,
    title: "Kvantna fizika 2",
    category: "Napredna fizika",
    price: 11.50,
    image: "./images/book_placeholder.png",
    description: "",
  },
  {
    id: 9,
    title: "Uvod u fiziku 1",
    category: "Uvod u fiziku",
    price: 11.50,
    image: "./images/book_placeholder.png",
    description: "",
  },
  {
    id: 10,
    title: "Uvod u fiziku 2",
    category: "Uvod u fiziku",
    price: 11.50,
    image: "./images/book_placeholder.png",
    description: "",
  },
  {
    id: 11,
    title: "Osnove fizike 1",
    category: "Uvod u fiziku",
    price: 11.50,
    image: "./images/book_placeholder.png",
    description: "",
  },
  {
    id: 12,
    title: "Osnove fizike 2",
    category: "Uvod u fiziku",
    price: 11.50,
    image: "./images/book_placeholder.png",
    description: "",
  },
  {
    id: 13,
    title: "Linearna algebra 1",
    category: "Matematika",
    price: 11.50,
    image: "./images/book_placeholder.png",
    description: "",
  },
  {
    id: 14,
    title: "Linearna algebra 2",
    category: "Matematika",
    price: 11.50,
    image: "./images/book_placeholder.png",
    description: "",
  },
  {
    id: 15,
    title: "Matematička analiza 1",
    category: "Matematika",
    price: 11.50,
    image: "./images/book_placeholder.png",
    description: "",
  },
  {
    id: 16,
    title: "Matematička analiza 2",
    category: "Matematika",
    price: 11.50,
    image: "./images/book_placeholder.png",
    description: "",
  },
  {
    id: 17,
    title: "Diferencijalna geometrija",
    category: "Matematika",
    price: 11.50,
    image: "./images/book_placeholder.png",
    description: "",
  },
  {
    id: 18,
    title: "Zbirka formula iz matematike",
    category: "Ostali priručnici",
    price: 11.50,
    image: "./images/book_placeholder.png",
    description: "",
  },
  {
    id: 19,
    title: "Zbirka formula iz fizike",
    category: "Ostali priručnici",
    price: 11.50,
    image: "./images/book_placeholder.png",
    description: "",
  },
];
