// proizvodi.js
window.products = [
  {
    id: 1,
    author: "Autor autor",
    title: "Opća fizika 1",
    category: "Napredna fizika",
    price: 13.90,
    image: "./images/book_placeholder.png",
    description: "Opis",
    longDescription: "Detaljniji opis proizvoda.",
    sku: "BK-000123",
    availability: "Na skladištu",
  },
  {
    id: 2,
    author: "Autor autor",
    title: "Opća fizika 2",
    category: "Napredna fizika",
    price: 11.50,
    image: "./images/book_placeholder.png",
    description: "Opis",
  },
  {
    id: 3,
    author: "Autor autor",
    title: "Opća fizika 3",
    category: "Napredna fizika",
    price: 14.80,
    image: "./images/book_placeholder.png",
    description: "Opis",
  },
  {
    id: 4,
    author: "Autor autor",
    title: "Opća fizika 4",
    category: "Napredna fizika",
    price: 14.80,
    image: "./images/book_placeholder.png",
    description: "",
  },
  {
    id: 5,
    author: "Autor autor",
    title: "Elektrodinamika 1",
    category: "Napredna fizika",
    price: 11.50,
    image: "./images/book_placeholder.png",
    description: "",
  },
  {
    id: 6,
    author: "Autor autor",
    title: "Elektrodinamika 2",
    category: "Napredna fizika",
    price: 11.50,
    image: "./images/book_placeholder.png",
    description: "",
  },
  {
    id: 7,
    author: "Autor autor",
    title: "Statistička fizika 1",
    category: "Napredna fizika",
    price: 11.50,
    image: "./images/book_placeholder.png",
    description: "",
  },
  {
    id: 8,
    author: "Autor autor",
    title: "Statistička fizika 2",
    category: "Napredna fizika",
    price: 11.50,
    image: "./images/book_placeholder.png",
    description: "",
  },
  {
    id: 9,
    author: "Autor autor",
    title: "Kvantna fizika 1",
    category: "Napredna fizika",
    price: 11.50,
    image: "./images/book_placeholder.png",
    description: "",
  },
  {
    id: 10,
    author: "Autor autor",
    title: "Kvantna fizika 2",
    category: "Napredna fizika",
    price: 11.50,
    image: "./images/book_placeholder.png",
    description: "",
  },
  {
    id: 10,
    author: "Autor autor",
    title: "Uvod u fiziku 1",
    category: "Uvod u fiziku",
    price: 11.50,
    image: "./images/book_placeholder.png",
    description: "",
  },
  {
    id: 11,
    author: "Autor autor",
    title: "Uvod u fiziku 2",
    category: "Uvod u fiziku",
    price: 11.50,
    image: "./images/book_placeholder.png",
    description: "",
  },
  {
    id: 12,
    author: "Autor autor",
    title: "Osnove fizike 1",
    category: "Uvod u fiziku",
    price: 11.50,
    image: "./images/book_placeholder.png",
    description: "",
  },
  {
    id: 13,
    author: "Autor autor",
    title: "Osnove fizike 2",
    category: "Uvod u fiziku",
    price: 11.50,
    image: "./images/book_placeholder.png",
    description: "",
  },
  {
    id: 14,
    author: "Autor autor",
    title: "Linearna algebra 1",
    category: "Matematika",
    price: 11.50,
    image: "./images/book_placeholder.png",
    description: "",
  },
  {
    id: 15,
    author: "Autor autor",
    title: "Linearna algebra 2",
    category: "Matematika",
    price: 11.50,
    image: "./images/book_placeholder.png",
    description: "",
  },
  {
    id: 16,
    author: "Autor autor",
    title: "Matematička analiza 1",
    category: "Matematika",
    price: 11.50,
    image: "./images/book_placeholder.png",
    description: "",
  },
  {
    id: 17,
    author: "Autor autor",
    title: "Matematička analiza 2",
    category: "Matematika",
    price: 11.50,
    image: "./images/book_placeholder.png",
    description: "",
  },
  {
    id: 18,
    author: "Autor autor",
    title: "Diferencijalna geometrija",
    category: "Matematika",
    price: 11.50,
    image: "./images/book_placeholder.png",
    description: "",
  },
  {
    id: 19,
    author: "Autor autor",
    title: "Zbirka formula iz matematike",
    category: "Ostali priručnici",
    price: 11.50,
    image: "./images/book_placeholder.png",
    description: "",
  },
  {
    id: 20,
    author: "Autor autor",
    title: "Zbirka formula iz fizike",
    category: "Ostali priručnici",
    price: 11.50,
    image: "./images/book_placeholder.png",
    description: "",
  },
];
